### ISSUE TITLE
Why protobuf 2 ?

### ISSUE THREAD

**Issue by rom1504** [datrs/dat-network-protocol#7]

**Comment by yoshuawuyts** [comment]
My understanding is that protobuf 3 contains additional syntax to define RPC services, which isn't necessary in a Hypercore context. Also Dat development was started before protobuf 3 was released to the public, meaning it wasn't even an option at the time. We stick to what the protocol uses, which is protobuf 2.

Hope this answers your question!

**Comment by rom1504** [comment]
Ah ok, I didn't know dat was that old.
For me one of the main fix that protobuf 3 contains is that every field is optional.
That fixes the issue in which in protobuf 2 you actually have to indicate that every field is optional if you which to remove it someday.

But anyway it's not compatible with protobuf 2, so that would be a major change of the protocol. Probably not worth it at this point.

Thank for the explanation.

**Comment by yoshuawuyts** [comment]
> For me one of the main fix that protobuf 3 contains is that every field is optional.
That fixes the issue in which in protobuf 2 you actually have to indicate that every field is optional if you which to remove it someday.

Ah okay, I didn't realize that -- thanks for explaining!
